baseURL = "https://github.com/rcjach/hugo-webslides.git"
disableKinds = ["sitemap", "RSS"]
features = ["webslides.js", "pre-made template", "shortcodes"]
languageCode = "en-us"
tags = ["slide", "presentation", "responsive", "landing page"]
theme = "hugo-webslides"
themesDir = "../.."
title = "A Hugo theme for creating Webslides.js presentations"
[markup]
defaultMarkdownHandler = "blackfriday"
[markup.goldmark.renderer]
unsafe = true
[params]
author = "RCJacH"
homepage = "RCJacH.github.io"
[params.webslides]
autoslide = false
banner = false
changeOnClick = false
disableLoop = false
disableNavigateOnScroll = false
hideIndex = false
minWheelDelta = 40
scrollWait = 450
slideOffset = 50
slideshow = true
vertical = false
